### ISSUE TITLE
Update `README.md` with API usage and verification instructions

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#25] opened 2022-08-04 13:52 UTC
## Description

This is a required documentation piece for the tech challenge, and I want to make sure we remember to do it well as it's the primary interface that will be interacted with during our technical evaluation.

There are a few scripts that we'll need, this card is just for any API usage and verification instructions.

Don't worry too much about wording it "nice", @malak-coforma or other tech writers will go in afterwards to make sure the writing is cohesive and polished. ✍ 

## Requirements

- [ ] Give technical steps related to verifying APIs (ie: we have three roles, probably need to explain how to query as all three roles)
- [ ] Give technical steps related to querying the database
- [ ] Any other technical steps related to evaluating our solution
- [ ] List out ids for the patient status, disasters, and facilites that are available
- [ ] If there are any decisions that were made during this script creation, please note them for documentation :v:
- [ ] Add instructions for this script to `README.md`

## Next Steps

- [ ] Ask someone else on the team to test it in a fresh environment

### From the instructions document

> To install and evaluate the product, the Quoter’s repository shall include a README.MD file which includes:
> - The location of a script in the Quoter’s GitHub repository for:
>   - Installing and configuring the AWS environment.
>   - Compiling (as necessary) and deploying the solution. The Government will not accept pre-compiled solutions from the Quoter.
>   - Running tests associated with the solution.
>   - Removing the installed solution from the AWS environment.
> - **Instructions for how to verify APIs, and query the contents of the database, or any other manual steps necessary to evaluate the solution.**

**Comment by malak-coforma** [comment] 2022-08-05 19:31
Updated requirements to reflect conversation about need for specifying available IDs from https://coforma.slack.com/archives/C01C6JHK0BV/p1659726925056719?thread_ts=1659725582.886849&cid=C01C6JHK0BV

**Comment by TheDanMiller** [comment] 2022-08-11 23:53
Duplicate of 106

**Closed by TheDanMiller** 2022-08-11 23:53 UTC
Labels: documentation, duplicate
